
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riwyowmbpwkqgjkbdxkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpd3lvd21icHdrcWdqa2JkeGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5OTc5MTYsImV4cCI6MjA1NzU3MzkxNn0.sNZ2exqRF4_XR8rOUZTEBhTqcjOVxCeYe8Yno361o6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
